### PR TITLE
Allow child image sharp on arrays of images

### PR DESCRIPTION
**Pull request by denisgoryaynov**
Right now it's not possible to query File properties on arrays of images, for example this results in an error: 

```graphql
{
  allStrapiArticle {
    edges {
      node {
        multipleImages {
          publicURL
          childImageSharp {
            ...
          }
        }
      }
    }
  }
}
```

this pull request fixes the issue by allowing to query a localFile field on arrays of images:

```graphql
{
  allStrapiArticle {
    edges {
      node {
        multipleImages {
          localFile {
            publicURL
            childImageSharp {
               ...
            }
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by aramkoukia** [comment]
Nice. When will this be available?

**Comment by beve** [comment]
Really nice. Hope it will be merged.

**Comment by omerman** [comment]
Any news on this??

**Comment by Naismith** [comment]
@soupette this PR does not appear to work with childImageSharp plugin for optimizing images.

**Comment by soupette** [comment]
@Naismith do you suggest to close it?

**Comment by denisgoryaynov** [comment]
@Naismith did you find any issues? I'm currently using this version on my company's website with no problems but there may be some use cases I didn't consider when modifying the code, I can take a look and try to fix the issues if you have any feedback

**Comment by Naismith** [comment]
@denisgoryaynov when looking at Gatsby's __graphql route, the images did not seem to have a localFile key, so I was unable to use the childImageSharp plugin on the images. I will test again tonight to make sure I didn't do anything wrong. @soupette would you confirm if you have any issues?

**Comment by denisgoryaynov** [comment]
@Naismith I don't know if this is the case, but the localFile key exists only on arrays of images, when using a single image you can access fields like publicURL directly from the image
```
allStrapiArticle {
  nodes {
    SingleImage {
      publicURL
    }
    MultipleImages {
       localFile {
         publicURL
       }
    }
  }
}
```

**Comment by Naismith** [comment]
Just tested again, it seems to be working fine for me now. I do wonder if there's a way we can do this without the 'localFile'. So that we can have a similar API with multipleImages as we do with singleImages.

But if @soupette is cool with how the current API is for multiple images, then I say it's good.

**Comment by likw1d** [comment]
This is a great feature and should be merged when its ready and tested, but when i was trying out the new versions i started getting errors when running `gatsby develop` and could not pull any info from Strapi:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "<my-field-name>" on type "Query".
```

Now, i am not an expert and this could be something i am doing wrong but here is what i saw:

1. Uninstall the existing `gatsby-source-strapi` module:
`npm uninstall gatsby-source-strapi`
2. Install the new version from the forked repo:
`npm install --save https://github.com/denisgoryaynov/gatsby-source-strapi`
3. Try to run `gatsby develop` and get the above errors.

When i reverted the change and went back to version 0.0.10, everything stated working again.

Any suggestions are welcome :)

**Comment by denisgoryaynov** [comment]
@likw1d the master branch of my fork is missing the compiled files that you would normally have when installing gatsby-source-strapi from npm, for now you can just add this line to your package.json:

`"gatsby-source-strapi": "https://github.com/denisgoryaynov/gatsby-source-strapi.git#build",`

and then run `npm i`. All this does is pulling the files from the 'build' branch which has the required files to make the plugin work.

**Comment by likw1d** [comment]
Thank you @denisgoryaynov, i just tried it again following your suggestion and works like a charm!

**Comment by soupette** [comment]
@Naismith  Let's release it!

**Comment by joe-thong** [comment]
when are we tagging a 0.11 release? can't seem to install straight from yarn add https://github.com/strapi/gatsby-source-strapi.git.  

Constantly getting 
`Cannot query field "allStrapiPost" on type "Query".`

Using 
`yarn add https://github.com/denisgoryaynov/gatsby-source-strapi.git#build` instead for now

Thanks @denisgoryaynov for your work

**Comment by mfuezesi** [comment]
This issue is still present.

Thanks to @denisgoryaynov, your solution works great!

**Comment by jossydeleon** [comment]
Thanks @denisgoryaynov Working like a charm, I had to use your forked version because this problem still persist on current version 0.12

**Pull request merged**
