### PR TITLE
Fix: File nodes are not created for multiple file fields

### PR DESCRIPTION
**Pull request by joshdcuneo**
Hi,

Thanks for your work on this plugin. 

Just opening a PR to address [this issue](https://github.com/strapi/gatsby-source-strapi/issues/79).

Fields with arrays of files were not handled correctly in extractFields resulting in file nodes not being generated. This PR should resolve that as well as some console.time calls with duplicate identifiers.

Let me know if you need anything to get it merged.

Josh

### CODE REVIEW

**Comment by joshdcuneo** [comment]
[This is the timer issue that is also addressed here](https://github.com/strapi/gatsby-source-strapi/issues/65)

**Comment by darthzyklus** [comment]
@joshdcuneo hey this is awesome, I have a use case for the multiple files and I'm don't get the nodes with the childImageSharp, maybe this solves this issue. I will test your fork

**Comment by darthzyklus** [comment]
@joshdcuneo the node for an individual media file is broken, I couldn't even compile my gatsby project because of a failed qraphql query to this kind of node (it was working before using the fork with this PR)

**Comment by joshdcuneo** [comment]
@darthzyklus this PR and the master branch of my fork have diverged a little but but seem to be working for single file nodes for me?

The fork has some additional changes that I think would not be compatible with gatsby < 2.0.

Screen Shot 2019-09-15 at 7 29 43 am

**Comment by darthzyklus** [comment]
@joshdcuneo can you try with an image and the sharp image plugin? for example:
```
query {
   allStrapiEvent {
     edges {
        node {
           poster {
              childImageSharp {
                 fluid {
                     src
                 }
              }
           }
        }
     }
  }
}
```

**Comment by joshdcuneo** [comment]
@darthzyklus sorry for the confusion. I forgot updating the fork would affect this PR and made some changes that I need for work. I am going to close this PR and will open another one later once I get a chance to look at this again.

The fork should be working currently, child image sharp is available on the localFile field of each file node.

**Pull request closed without merging**
