### PR TITLE
Publication state support for fetching draft content

### PR DESCRIPTION
**Pull request by cempesket**
- publication state added to config
- publication state added to api params
- readme updated

### CODE REVIEW

**Comment by RobinSJames** [comment]
Please add this feature - this is exactly what I need to allow previews via webhooks.

**Review by RobinSJames — COMMENTED** [review]
Simple yet perfect 👍 
local changes work for me.

**Comment by dvakatsiienko** [comment]
I need this also! Push the PR

**Review by RobinSJames — APPROVED** [review]

**Comment by jestapinski** [comment]
Can we get this in and built? Looking to use this feature soon if possible

**Comment by remidej** [comment]
Thank you for your contribution 🙂 

Unfortunately I won't merge it, because we have accepted another PR that provides that functionality with a bit more flexibility: #193. It allows you to set any query string you want for each content type.

I have opened #217 to add an example to the docs of how draft & publish works. But the good news is that with the new v1, you can already use this to fetch draft content

**Pull request closed without merging**
