### PR TITLE
issue #144 fix request

### PR DESCRIPTION
**Pull request by burlakko**
Fixes cache problem described in [https://github.com/strapi/gatsby-source-strapi/issues/144](https://github.com/strapi/gatsby-source-strapi/issues/144)

### CODE REVIEW

**Comment by hashinteractive** [comment]
I can confirm this fixes issue #141 and #144 

Can we get this merged into the repo?

**Comment by burlakko** [comment]
@lauriejim please please please can somebody from your team review this request? It fixes an actual bug.

**Comment by manuelojeda** [comment]
Can we make a CC to @ostrgard @tscheiki ?
This patch is needed ASAP!

**Comment by ostrgard** [comment]
Sorry there's not much I can do. I'm not on the Strapi team. 

**I would however suggest that you migrate to [`gatsby-source-graphql`](https://www.gatsbyjs.com/plugins/gatsby-source-graphql/) and follow [this guide](https://levelup.gitconnected.com/strapi-dynamic-zone-and-gatbsy-image-6f29b6bb0f0) to support images**. I've expressed my confusion to the Strapi team about `gatsby-source-strapi` being the official support by Strapi, when using `gatsby-source-graphql` have so many benefits over it:
- Actual union types for dynamic zones and components. Since `gatsby-source-graphql` doesn't use union types, you can actually have conflicting components in dynamic zones (if components share field names that differ in type.)
- `gatsby-source-strapi` creates a graphql schema based on your data. This means that if your frontend queries a field that you've created in Strapi, but don't have data for in your database yet, your frontend won't build. I honestly find the Strapi graphql endpoint really nice, and cannot fathom why you would prefer to _generate a schema based on raw data_ rather than stitch some of the awesome work already done in Strapi.

I recall listing more benefits when discussing this with the team on slack, but these messages are lost since the slack channel is not on a paid plan. My offer to the Strapi team of building a more plug-able replacement still stands if they're open to deprecating this repo. Otherwise I just think it adds to more confusion in the ecosystem.

**Comment by hashinteractive** [comment]
> **I would however suggest that you migrate to [`gatsby-source-graphql`](https://www.gatsbyjs.com/plugins/gatsby-source-graphql/) and follow [this guide](https://levelup.gitconnected.com/strapi-dynamic-zone-and-gatbsy-image-6f29b6bb0f0) to support images**. I've expressed my confusion to the Strapi team about `gatsby-source-strapi` being the official support by Strapi, when using `gatsby-source-graphql` have major benefits:

Is this the general consensus to start migrating to `gatsby-source-graphql`. Since `gatsby-source-strapi` is not a core plugin for strapi I would imagine it's not getting a lot of attention. This is a pretty simple PR that hasn't been merged for months so loosing confidence that a breaking change would quickly be merged.

**Comment by ostrgard** [comment]
> Is this the general consensus to start migrating to `gatsby-source-graphql`? Since `gatsby-source-strapi` is not a core plugin for strapi I would imagine it's not getting a lot of attention. This is a pretty simple PR that hasn't been merged for months so loosing confidence that a breaking change would quickly be merged.

I'm unsure wether or not there's even enough people running a Strapi+Gatsby stack, since the team does not prioritise this. If that's the case I agree that they should spend their time elsewhere. I've seen people mention (on slack, various blog posts and github) that they've migrated to `gatsby-source-graphql`, but not enough to call it actual consensus in my opinion. I think people who research on a Strapi+Gatsby stack won't think twice about going with `gatsby-source-strapi`, since it's the official recommendation (maybe that's an overstatement, but they do provide a guide for this stack using `gatsby-source-strapi`). You won't find out about these caveats until you've spend quite some time implementing and start running into problems.

**Comment by alexandrebodin** [comment]
Hi! I refactored quite a lot of code and integrated changes to support what you have done. (using localFile to follow gatsby's examples)

Your code was really helpful in anycase ! Thanks a lot for your contributions.

I released v1.0.0-alpha.0 with the latest changes. please try it out to validate things work for you so we can move release as latest !

**Comment by burlakko** [comment]
@alexandrebodin I tried the 1.0.0-alpha.0 version on a new clean project and the plugin does not provide images at all.
e.g.
```
import React from 'react'
import { graphql } from 'gatsby'

function Component({ data: { singleType } }) {
  console.log(singleType.image)
  return <div/>
}

const query = graphql`
  query singleTypeQuery {
    singleType: strapiSingleType {
      image {
        childImageSharp {
          fluid(maxWidth: 1920) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  }
`

export default Intro
export { query }

```

`singleType.image` is always null even so it's definitely present in api. Also tried with custom graphql schema with same result.

**Comment by alexandrebodin** [comment]
@burlakko As described in the readme you need to use the localFile field inside the image field to access this 👍

**Comment by burlakko** [comment]
Tried
```
image {
  localFile {
    publicURL
  }
}
```
Got `Cannot query field "publicURL" on type "File".`

**Comment by alexandrebodin** [comment]
Hi @burlakko this is precisely what I am doing. And I am getting this
Screenshot 2020-11-26 at 18 38 50


Can you verify the version you are using (lock file) ?

**Comment by burlakko** [comment]
Hi @alexandrebodin! For that project i reverted to previous version of plugin. Will try again on clean installation today or tomorrow

**Comment by alexandrebodin** [comment]
Hi @burlakko have you  been able to test ?

**Comment by burlakko** [comment]
@alexandrebodin Yes I did a while ago.
Added issue #166.
But i mainly use this plugin with custom graphql schema and wasn't able to configure this version to work with it. So I reverted to previous version.
Though if you could add a relevant example in readme, i will test again.

**Comment by alexandrebodin** [comment]
Hi, We just released the v1.0.0 fixing including this requested changes :)

**Pull request closed without merging**
