### PR TITLE
add support for irregular collection names

### PR DESCRIPTION
**Pull request by SimonThormeyer**
this is to add the option to have **collection names with irregular plurals** (such as person -> people) which occurs quite often in other languages (e. g. in German Person -> Personen).
Adding contentTypes with irregular plurals along regular ones can be done like this in gatsby-config.js:

```
contentTypes: [
        `article`, `user`,
        //for irregular collection names
        {
          name: `person`,
          plural: `people`
        }
      ],
```

I am using it and it is working.

as mentioned in [issue #113 ](https://github.com/strapi/gatsby-source-strapi/issues/113)

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @SimonThormeyer Can you explain why the pluralize function that is used is not enough your your usecase ? using pluralize person already becomes people doesn't it ?

**Comment by SimonThormeyer** [comment]
Hello @alexandrebodin,
Sure I will try and explain why I needed this.
And most likely you are right, the package pluralize probably pluralizes all English words well. I simply took the example from #113 without testing. Sorry for that!

My use case was that I had my collection names in German and I had a collection called 'Beitrag', its plural is 'Beitraege' which is irregular and not correctly pluralized by pluralize (will be 'Beitrags').
In that case I had wished for a possibility to customise my plural easily, which is enabled by this PR imo. 

That's it! :)

**Comment by alexandrebodin** [comment]
Ho ok I get your usecase @SimonThormeyer. So if I am not mistaken you modified the api routes on your own to matches the right naming ?

**Comment by SimonThormeyer** [comment]
That is correct, @alexandrebodin, if a content type contains a plural key, the api routes will be modified to match its value.
If it doesn't, the pluralize function is used just as before.

**Comment by alexandrebodin** [comment]
Would you mind renaming plural to endpoint ?

**Comment by SimonThormeyer** [comment]
Will do when I get back from holiday (which is next week Wednesday) if that is OK, don't have a computer with me :)

**Comment by SimonThormeyer** [comment]
Renamed plural to endpoint. Also adjusted the explanation in Readme.md.
Hope it makes sense this way!
Cheers

**Comment by SimonThormeyer** [comment]
> Sorry to be picky, But would you mind transforming the /singleTypes at the beginning of the function so they all are of the form { name, endpoint } ? thus making the rest of the code more consistent

Don't mind at all but I don't quite get what you mean I'm afraid, can you explain again? Did I understand correctly, the single types should have a customizable endpoint as well that can differ from their name and be of the format {name, endpoint}?

**Comment by alexandrebodin** [comment]
@SimonThormeyer Sorry If I wasn't clear enough ! I meant normalizing the inputs to be of the form name, endpoint so we use this everywhere else, sth like:

`gatsby-node.js`
```js

const normalizeContentType = opts => typeof opts === 'string' ? { name: opts, endpoint: pluralize(opts) } : opts;

exports.sourceNodes = async (ctx, opts) => {

  opts.contentTypes.map(ct => {
    fetchData({
      //...
      contentType: normalizeContentType(ct)
    });
  });
}
```

this way the data passed to fetch is always `{ name, endpoint }` . 

Hope this makes sense :)

**Comment by alexandrebodin** [comment]
Hi ! I refactored quite a lot of code and integrated changes to support what you have done.
I made the changes I requested to move forward

I released v1.0.0-alpha.0 with the latest changes. please try it out to validate things work for you so we can move release as latest !

**Comment by alexandrebodin** [comment]
Hi, We just released the v1.0.0 fixing including this requested changes :)

**Pull request closed without merging**
