### PR TITLE
remove duplicate header key

### LINKED ISSUE #215: Authentication to collectionTypes/singleTypes endpoints fail after successful request to /auth/local
The JWT-Token request seems to be successful according to build-log
```
...
success Authenticate Strapi User - 0.344s
...
```
and server-log
```
[2021-05-20T23:14:20.521Z] debug POST /auth/local (172 ms) 200
```
But the actual requests to acquire the collection data seems to be failing with an HTTP 403 error
```
[2021-05-20T23:30:31.364Z] debug GET /contact?_limit=1000 (36 ms) 403
[2021-05-20T23:30:31.368Z] debug GET /users?_limit=1000 (29 ms) 403
[2021-05-20T23:30:31.369Z] debug GET /article-feeds?_limit=1000 (34 ms) 403
[2021-05-20T23:30:31.372Z] debug GET /pages?_limit=1000 (28 ms) 403
[2021-05-20T23:30:31.374Z] debug GET /articles?_limit=1000 (16 ms) 403
[2021-05-20T23:30:31.374Z] debug GET /site-config?_limit=1000 (23 ms) 403
```
This only occurs with the new 1.0.0 release, the 1.0.0-alpha.1 worked and still works fine.

The only thing, that changed is the usage of `collectionTypes` instead of `contentTypes` in the gatsby-config.js
according to the README.md

## Context (Environment)

strapi 3.6.2 in both development and production mode with credentials passed in as environment variable or
inline ( tried both )

## Potential Fix

Found the method where the token is set in the request Header. It seems to be set with an additional `header` in the `Authorization` key.

### PR DESCRIPTION
**Pull request by kminhc**
Fixes #215

### CODE REVIEW

**Comment by remidej** [comment]
It looks like the problem still occurs for me, even with your change

**Comment by kminhc** [comment]
This seems strange. On my end this exact change makes it work, because the requestOptions then looks like this 
```
{"method":"GET","url":"https://example.com/articles","params":{"_limit":1000},"headers":{"Authorization":"Bearer  TOKEN"}}
```

instead of

```
{"method":"GET","url":"https://example.com/articles","params":{"_limit":1000},"headers":{"header":{"Authorization":"Bearer TOKEN"}}}
```

**Comment by raphacamilo** [comment]
This fix works well for me.

**Review by remidej — APPROVED** [review]
Thanks for your responses. I double checked and the problem was coming from my environment, so my bad!

The change looks good and fixes the problem. I'm not sure what caused the problem in this specific release though. But it seems ready to merge @alexandrebodin 🙂

**Pull request merged**
